language: python

env:
  global:
    - ODBCSYSINI=$TRAVIS_BUILD_DIR/odbcconfig
matrix:
  include:
#
#    - python: "2.7"
#      env:
#        - secure: "QUAD5FrpEyUSN+crGmTIA3yKVctkxqRXlc6t0421dF+/Sal0ed1H95ySNNgDDeXTfVxcrLpdf5zZCvPHXJeqb5z1v76LrnDzG/o1iV/R3avFMgWAo4B9OX8mgq/4nzs+pFR1HMeTh2aORVcCWnRsPwE6ZpDMh/Ho2uRSMy2ifRo="
#    - python: "3.4"
#      env:
#        - secure: "QUAD5FrpEyUSN+crGmTIA3yKVctkxqRXlc6t0421dF+/Sal0ed1H95ySNNgDDeXTfVxcrLpdf5zZCvPHXJeqb5z1v76LrnDzG/o1iV/R3avFMgWAo4B9OX8mgq/4nzs+pFR1HMeTh2aORVcCWnRsPwE6ZpDMh/Ho2uRSMy2ifRo="
    - python: "2.7"
      env:
        - secure: "NrbXBxe4OnR3ak9WCa31GtED82s5D59/auWccXyDfnvGTgtkxqk7AtKDc7QBzGKOS9Hkj2GTC3li9OjK2ZQftvvDt/RVHvv2m7cK3ejjVsnG6Gf2lxUnyGsUqnWFnLmHjGZlWbc0vQ3sKI7cj7w0/tigfZ5GNwAqSn61tX8pzdI="
    - python: "3.4"
      env:
        - secure: "NrbXBxe4OnR3ak9WCa31GtED82s5D59/auWccXyDfnvGTgtkxqk7AtKDc7QBzGKOS9Hkj2GTC3li9OjK2ZQftvvDt/RVHvv2m7cK3ejjVsnG6Gf2lxUnyGsUqnWFnLmHjGZlWbc0vQ3sKI7cj7w0/tigfZ5GNwAqSn61tX8pzdI="
    # turbodbc test run, currently only with 2.7
    - python: "2.7.6"
      env:
        - secure: "RgjJWQbuzrVN/YDNIG9ftx4CYTXD2oD3iuML0DnTrV2RpLivGyXdGGbhPl8v+7L46VOAnqwT2+jwOnxb2M4HRLtiOY3ixSJXmfN2i5VwK2lKyF2Agewec3D7bnp697rxTfdI1ejBFo3FwtGejn3dAGZ2KR73w4lY74Qd81ff4nA="
      before_install:
        - sudo apt-get install libboost-all-dev
      install:
        - pip install -r requirements_extras.txt
dist: trusty
install:
  - sudo apt-get install -y unixODBC unixODBC-dev
  - ./fix_unixodbc_so.sh
  - pip install -r requirements.txt --allow-external pyodbc --allow-unverified pyodbc 
  - pip install -r requirements_test.txt
  - pip install coveralls
before_script:
  # append db driver location to odbc config
  - echo DRIVER=$TRAVIS_BUILD_DIR/driver/libexaodbc-uo2214.so >> odbcconfig/odbcinst.ini
script: 
  - py.test --dropfirst --cov-config=.coveragerc --cov=sqlalchemy_exasol --dburi "${TESTDB#*=}"
after_success:
  - coveralls
  # revert changes to odbc config to avoid dirty tag on deploy
  - git checkout odbcconfig/odbcinst.ini
deploy:
  provider: pypi
  user: BY-jk
  password:
    secure: SNyP2s6DV0Hm/gcFEk0iqllmeIvRU16YI/Gn7SF6+kT3EXyzE3gkPq0v/VRV4+n6wpNT2FELl69tZL87vXtYPxEiLXzSsWAuKmy9dapbf1bjzLjr3fVepEpesLPivYFFxToYa7osjunVVKxRNOzW5epCpRcWJP8bDiJKxH5BF38=
  on:
    all_branches: true
    tags: true
    repo: blue-yonder/sqlalchemy_exasol
