language: python
python:
  - "2.7"
env:
  - secure: "P9LU3GVl7m44h/LpqOBsP3CnRnMlkz8fd0FQLVjcq8ZE50ERwLfluQXGEtT/wEtgOVUQqP6A69QJDBmn9Z2HUGQZ/aoiSVApZaPrxlRwPfa4Nbk8aXeGpIPzDChCbd1cvvcZK/RRZyWFPU5yX4VKm+UIbIg/Jw3e/QGZmkGF5I8=" ODBCSYSINI=odbcconfig/
# command to install dependencies
install:
  - sudo apt-get install unixODBC unixODBC-dev
  - pip install -r test_requirements.txt
  - python setup.py -q install
before_script:
  # append Test DB connection string to setup.cfg
  - echo $TESTDB >> setup.cfg
  # append Driver location to odbc config
  - echo DRIVER=$TRAVIS_BUILD_DIR/driver/libexaodbc-uo2214.so >> odbcconfig/odbcinst.ini
  - cat odbcconfig/odbcinst.ini
  
# command to run tests
script: python run_tests.py
