language: python
python:
  - '2.7'
env:
  global:
  - ODBCSYSINI=$TRAVIS_BUILD_DIR/odbcconfig
  - secure: "P9LU3GVl7m44h/LpqOBsP3CnRnMlkz8fd0FQLVjcq8ZE50ERwLfluQXGEtT/wEtgOVUQqP6A69QJDBmn9Z2HUGQZ/aoiSVApZaPrxlRwPfa4Nbk8aXeGpIPzDChCbd1cvvcZK/RRZyWFPU5yX4VKm+UIbIg/Jw3e/QGZmkGF5I8="
install:
  - sudo apt-get install unixODBC=2.2.14p2-5ubuntu3 unixODBC-dev=2.2.14p2-5ubuntu3
  - ./fix_unixodbc_so.sh
  - pip install -r test_requirements.txt
  - pip install coveralls
  - python setup.py -q install
before_script:
  - echo DRIVER=$TRAVIS_BUILD_DIR/driver/libexaodbc-uo2214.so >> odbcconfig/odbcinst.ini
script: 
  - coverage run --source=sqlalchemy_exasol run_tests.py -v --dburi "${TESTDB#*=}"
after_success: 
  - coveralls
