language: python
dist: trusty

python:
  - "2.7"
  - "3.4"

env:
  global:
    - ODBCSYSINI=$TRAVIS_BUILD_DIR/odbcconfig
    # EXA5_TESTDB
    - secure: "f6IiDtarGpr32z9BDtnjPS7dfomRnJvY6T6cxbgC/MJCxLBda5Sz4GFQNwwUnDqJ5wXPyKMWu3geFbdqJqSBiY/TTj19sVmrOYrPQLaH/JyHKiVIWL3hUdkdTNlCNuceCvBZJ5spihhKNJJ5NagYmZEIzleiMG/+SQFGU0sq1kY="
  matrix:
    - TESTDB="${EXA5_TESTDB}" EXA_5=nil EXTRA_REQUIREMENTS=""
    - TESTDB="${EXA5_TESTDB}" EXA_5=nil EXTRA_REQUIREMENTS="-r requirements_extras.txt"

matrix:
  exclude:
    - python: "3.4"
      env: TESTDB="${EXA5_TESTDB}" EXA_5=nil EXTRA_REQUIREMENTS="-r requirements_extras.txt"

before_install:
  - sudo apt-get install -y unixODBC unixODBC-dev libboost-all-dev
  - ./fix_unixodbc_so.sh

install:
  - pip install -r requirements.txt --allow-external pyodbc --allow-unverified pyodbc 
  - pip install -r requirements_test.txt $EXTRA_REQUIREMENTS
  - pip install coveralls

before_script:
  # append db driver location to odbc config
  - echo DRIVER=$TRAVIS_BUILD_DIR/driver/libexaodbc-uo2214.so >> odbcconfig/odbcinst.ini

script: 
  - py.test --dropfirst --cov-config=.coveragerc --cov=sqlalchemy_exasol --dburi "${TESTDB#*=}"

after_success:
  - coveralls
  # revert changes to odbc config to avoid dirty tag on deploy
  - git checkout odbcconfig/odbcinst.ini

deploy:
  provider: pypi
  user: BY-jk
  password:
    secure: SNyP2s6DV0Hm/gcFEk0iqllmeIvRU16YI/Gn7SF6+kT3EXyzE3gkPq0v/VRV4+n6wpNT2FELl69tZL87vXtYPxEiLXzSsWAuKmy9dapbf1bjzLjr3fVepEpesLPivYFFxToYa7osjunVVKxRNOzW5epCpRcWJP8bDiJKxH5BF38=
  on:
    all_branches: true
    tags: true
    repo: blue-yonder/sqlalchemy_exasol
