language: python
python:
  - '2.7'
  - '3.4'
env:
  global:
    - ODBCSYSINI=$TRAVIS_BUILD_DIR/odbcconfig
  matrix:
    - secure: "YqIgV0u7mmR6jlKAnco4RgQ9ZJZwogjf4YafeUU13a+S0oRWwYnGrUNwyNoy+4HjjO12aPV5liJg6IoKpBTthwpRd4BEK95xR+U3O/Q4xLzbCY+qIfwIwxwsMd+PPKeUb1BFx+JJtAMvkfafUPn8ksAo8rkXxIfAbM/NdCNUUbA="
    - secure: "dxIMxYjPYH1P5Z7oldg2/fZilaVONrRp+Cbg/2gSwhgqpIYsH7RAyw6qtIdCWUr9+tt8zH3R8U1twm7vsZQZoSq4W+TGVddvrul/9XJJWhHJG34+knWNjfoB2Hoa7yJcENTwD91y9+5VMECwh/+KQ7ErAwftNgjzqB95G1eWRmc="
install:
  - sudo apt-get install unixODBC=2.2.14p2-5ubuntu3 unixODBC-dev=2.2.14p2-5ubuntu3
  - ./fix_unixodbc_so.sh
  - pip install -r requirements_test.txt
  - pip install python-coveralls
  - python setup.py -q install
before_script:
  # append db driver location to odbc config
  - echo DRIVER=$TRAVIS_BUILD_DIR/driver/libexaodbc-uo2214.so >> odbcconfig/odbcinst.ini
script: 
  - py.test --dropfirst --cov-config=.coveragerc --cov=sqlalchemy --dburi "${TESTDB#*=}"
after_success: 
  - coveralls
  # revert changes to odbc config to avoid dirty tag on deploy
  - git checkout odbcconfig/odbcinst.ini
deploy:
  provider: pypi
  user: BY-jk
  password:
    secure: SNyP2s6DV0Hm/gcFEk0iqllmeIvRU16YI/Gn7SF6+kT3EXyzE3gkPq0v/VRV4+n6wpNT2FELl69tZL87vXtYPxEiLXzSsWAuKmy9dapbf1bjzLjr3fVepEpesLPivYFFxToYa7osjunVVKxRNOzW5epCpRcWJP8bDiJKxH5BF38=
  on:
    all_branches: true
    tags: true
    repo: blue-yonder/sqlalchemy_exasol
