language: generic
dist: trusty
sudo: required
group: deprecated-2017Q2

env:
  global:
    - ODBCSYSINI=$TRAVIS_BUILD_DIR/odbcconfig
    # EXAPWD
    - secure: "HC2JuDQ0DLO35eG2ZJCO/9Kntgk+MqaEylsDo0lfjSAbOvgncgh7ljyq+1anCC9r3zfPOISWU3ul6BARaDIbnUATguN2/HVQKWLFB+uu38lcP/c46aTYsMh6jH/eURjJBPfCWosvs02BXpKMphHd+dmPG+XrizzzBU35w2w6kQo="
    # EXAUID
    - secure: "M0TKnrWXD97TT2QXKrujBQn9vK19hScY7Re+j6ipuok63dGOweO8FPmrE2Vf5r8ks+zxEgLzDaEsIqIYdpGnP6R8MGhLV0O9wexNX9gt86wSfme8qQ35uBypgkFT4WJ4hTy6ojEbcO6xMRJY7GVYUv50Q05TRlmnnnKcPpVGhfo="
    # EXAHOST
    - secure: "SjLko6qL+YwJfotBb7/vwjAUuLGfKcNdKoc2uC90ZtFuvKeL/hf+pws++IO0wmJa6RQ92lWD35IaFAi7FsJCi4Om1TFoR8ppw4SZEvj2jMVF01uXegUuuAczrnzRtoJEwpj8GVSxMTiOdRFWIW7rk3yB84omvmkQizVZd/bpilU="
  matrix:
    - TESTDB="exa+pyodbc://${EXAUID}:${EXAPWD}@${EXAHOST}/${EXAUID}?CONNECTIONLCALL=en_US.UTF-8" EXTRA_REQUIREMENTS="" PYTHON_VERSION="python2.7"
    - TESTDB="exa+pyodbc://${EXAUID}:${EXAPWD}@${EXAHOST}/${EXAUID}?CONNECTIONLCALL=en_US.UTF-8" EXTRA_REQUIREMENTS="" PYTHON_VERSION="python3.4"
    - TESTDB="exa+turbodbc://${EXAUID}:${EXAPWD}@${EXAHOST}/${EXAUID}?CONNECTIONLCALL=en_US.UTF-8" EXTRA_REQUIREMENTS="-r requirements_extras.txt" PYTHON_VERSION="python2.7"
    - TESTDB="exa+turbodbc://${EXAUID}:${EXAPWD}@${EXAHOST}/${EXAUID}?CONNECTIONLCALL=en_US.UTF-8" EXTRA_REQUIREMENTS="-r requirements_extras.txt" PYTHON_VERSION="python3.4"

before_install:
  - sudo apt-get install python3-dev python-dev
  - virtualenv -p ${PYTHON_VERSION} venv && . venv/bin/activate
  - python --version
  - pip install setuptools
  - sudo apt-get install -y unixODBC unixODBC-dev libboost-all-dev libmyodbc
  - ./fix_unixodbc_so.sh

install:
  - pip install -r requirements.txt --allow-external pyodbc --allow-unverified pyodbc
  - pip install -r requirements_test.txt $EXTRA_REQUIREMENTS
  - pip install coveralls
  - pip freeze

before_script:
  # append db driver location to odbc config
  - echo DRIVER=$TRAVIS_BUILD_DIR/driver/libexaodbc-uo2214.so >> odbcconfig/odbcinst.ini

script:
  - python --version
  - py.test --dropfirst --cov-config=.coveragerc --cov=sqlalchemy_exasol --dburi "${TESTDB}"

after_success:
  - coveralls
  # revert changes to odbc config to avoid dirty tag on deploy
  - git checkout odbcconfig/odbcinst.ini

before_deploy:
  - sudo pip install twine

deploy:
  provider: pypi
  user: BY-jk
  skip_cleanup: true
  skip_upload_docs: true

  password:
    secure: SNyP2s6DV0Hm/gcFEk0iqllmeIvRU16YI/Gn7SF6+kT3EXyzE3gkPq0v/VRV4+n6wpNT2FELl69tZL87vXtYPxEiLXzSsWAuKmy9dapbf1bjzLjr3fVepEpesLPivYFFxToYa7osjunVVKxRNOzW5epCpRcWJP8bDiJKxH5BF38=
  on:
    all_branches: true
    tags: true
    repo: blue-yonder/sqlalchemy_exasol
