language: python
python:
  - '2.7'
  - '3.5'
env:
  global:
    - ODBCSYSINI=$TRAVIS_BUILD_DIR/odbcconfig
  matrix:
    - secure: "QUAD5FrpEyUSN+crGmTIA3yKVctkxqRXlc6t0421dF+/Sal0ed1H95ySNNgDDeXTfVxcrLpdf5zZCvPHXJeqb5z1v76LrnDzG/o1iV/R3avFMgWAo4B9OX8mgq/4nzs+pFR1HMeTh2aORVcCWnRsPwE6ZpDMh/Ho2uRSMy2ifRo="
    - secure: "NrbXBxe4OnR3ak9WCa31GtED82s5D59/auWccXyDfnvGTgtkxqk7AtKDc7QBzGKOS9Hkj2GTC3li9OjK2ZQftvvDt/RVHvv2m7cK3ejjVsnG6Gf2lxUnyGsUqnWFnLmHjGZlWbc0vQ3sKI7cj7w0/tigfZ5GNwAqSn61tX8pzdI="
install:
  - sudo apt-get install unixODBC=2.2.14p2-5ubuntu3 unixODBC-dev=2.2.14p2-5ubuntu3
  - ./fix_unixodbc_so.sh
  - pip install -r requirements.txt --allow-external pyodbc --allow-unverified pyodbc 
  - pip install -r requirements_test.txt
  - pip install python-coveralls
before_script:
  # append db driver location to odbc config
  - echo DRIVER=$TRAVIS_BUILD_DIR/driver/libexaodbc-uo2214.so >> odbcconfig/odbcinst.ini
script: 
  - py.test --dropfirst --cov-config=.coveragerc --cov=sqlalchemy --dburi "${TESTDB#*=}"
after_success: 
  - coveralls
  # revert changes to odbc config to avoid dirty tag on deploy
  - git checkout odbcconfig/odbcinst.ini
deploy:
  provider: pypi
  user: BY-jk
  password:
    secure: SNyP2s6DV0Hm/gcFEk0iqllmeIvRU16YI/Gn7SF6+kT3EXyzE3gkPq0v/VRV4+n6wpNT2FELl69tZL87vXtYPxEiLXzSsWAuKmy9dapbf1bjzLjr3fVepEpesLPivYFFxToYa7osjunVVKxRNOzW5epCpRcWJP8bDiJKxH5BF38=
  on:
    all_branches: true
    tags: true
    repo: blue-yonder/sqlalchemy_exasol
