language: python
dist: trusty
sudo: false

python:
  - "2.7"
  - "3.4"

env:
  global:
    - ODBCSYSINI=$TRAVIS_BUILD_DIR/odbcconfig
    # EXAPWD
    - secure: "HC2JuDQ0DLO35eG2ZJCO/9Kntgk+MqaEylsDo0lfjSAbOvgncgh7ljyq+1anCC9r3zfPOISWU3ul6BARaDIbnUATguN2/HVQKWLFB+uu38lcP/c46aTYsMh6jH/eURjJBPfCWosvs02BXpKMphHd+dmPG+XrizzzBU35w2w6kQo="
    # EXAUID
    - secure: "M0TKnrWXD97TT2QXKrujBQn9vK19hScY7Re+j6ipuok63dGOweO8FPmrE2Vf5r8ks+zxEgLzDaEsIqIYdpGnP6R8MGhLV0O9wexNX9gt86wSfme8qQ35uBypgkFT4WJ4hTy6ojEbcO6xMRJY7GVYUv50Q05TRlmnnnKcPpVGhfo="
    # EXAHOST
    - secure: "SjLko6qL+YwJfotBb7/vwjAUuLGfKcNdKoc2uC90ZtFuvKeL/hf+pws++IO0wmJa6RQ92lWD35IaFAi7FsJCi4Om1TFoR8ppw4SZEvj2jMVF01uXegUuuAczrnzRtoJEwpj8GVSxMTiOdRFWIW7rk3yB84omvmkQizVZd/bpilU="
    # EXAPWD6
    - secure: "CjjG4X6TJpeCwDvXSQnfwvev4FpDFClHhD4gkdMF7go5rookqQzBH4wzWy5bB0L2zsoEDV+EtmkB/v9CxQa3DLVthBGlzXZ9zOxBsD1LJ8Wr9YWnOiVMOnb3KKG1uWBGu0+XLGdUlXFQu/wFUUuvR+D1wARo+Mq81B+jGZv+OB4="
    # EXAUID6
    - secure: "Diw0AgGIbjd7WvD7B9HA2npPpXmgDgQBaU0dXWy1qGG5X4ZNVc0vmlviYLyUT3et1pHgGsoxXFa7P5KDPGNnh5Ni3vkQZ47epznooGvRI3fx5McCrNZb4YrfbX/R6EJzdLiY+yAurQ/kcCUdU6buEXWOwU0Vx/Os042zcfqYWtY="
    # EXAHOST6
    - secure: "OwYWkuDMxvBmKTpSP4ZZdpZlPmF1Nnu+eeimB4KlUmfU89FFf/tyUkr7CR27BxyIMB1VC5Gms6ukJS0A+0rGYkOj3p2lwIo+ymaE28g+KdbglQ2gh72xxkoIeJP3ujOZNqTGyU6Sibt+ORHlt99s3+WTorVLwZh3iSHjmFqovcc="
  matrix:
    # EXASOL 6 - pyodbc
    - TESTDB="exa+pyodbc://${EXAUID6}:${EXAPWD6}@${EXAHOST6}/TEST?CONNECTIONLCALL=en_US.UTF-8" EXTRA_REQUIREMENTS=""

addons:
  apt:
    packages:
      python3-dev
      python-dev
      unixodbc
      unixodbc-dev
      libboost-all-dev
      libmyodbc

before_install:
  - pip install setuptools
  - ./fix_unixodbc_so.sh

install:
  - pip install -r requirements.txt --allow-external pyodbc --allow-unverified pyodbc
  - pip install -r requirements_test.txt $EXTRA_REQUIREMENTS
  - pip install coveralls
  - pip freeze

before_script:
  # append db driver location to odbc config
  - echo DRIVER=$TRAVIS_BUILD_DIR/driver/libexaodbc-uo2214lv1.so >> odbcconfig/odbcinst.ini

script:
  - py.test --dropfirst --cov-config=.coveragerc --cov=sqlalchemy_exasol --dburi "${TESTDB}"

after_success:
  - coveralls
  # revert changes to odbc config to avoid dirty tag on deploy
  - git checkout odbcconfig/odbcinst.ini

before_deploy:
  - sudo pip install twine

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  skip_upload_docs: true
  user: BY-jk
  password:
    secure: SNyP2s6DV0Hm/gcFEk0iqllmeIvRU16YI/Gn7SF6+kT3EXyzE3gkPq0v/VRV4+n6wpNT2FELl69tZL87vXtYPxEiLXzSsWAuKmy9dapbf1bjzLjr3fVepEpesLPivYFFxToYa7osjunVVKxRNOzW5epCpRcWJP8bDiJKxH5BF38=
  on:
    tags: true
    repo: blue-yonder/sqlalchemy_exasol
