language: python
python:
  - "2.7"
env:
  global:
    - secure: "P9LU3GVl7m44h/LpqOBsP3CnRnMlkz8fd0FQLVjcq8ZE50ERwLfluQXGEtT/wEtgOVUQqP6A69QJDBmn9Z2HUGQZ/aoiSVApZaPrxlRwPfa4Nbk8aXeGpIPzDChCbd1cvvcZK/RRZyWFPU5yX4VKm+UIbIg/Jw3e/QGZmkGF5I8=" 
    - ODBCSYSINI=$TRAVIS_BUILD_DIR/odbcconfig
# command to install dependencies
install:
  - sudo apt-get install unixODBC=2.2.14p2-5ubuntu3 unixODBC-dev=2.2.14p2-5ubuntu3
  # fix unixODBC so.1 so.2 mess (EXASOL driver requires so.2 only so.1 are installed)
  - ./fix_unixodbc_so.sh
  # - odbcinst -j
  - pip install -r test_requirements.txt
  - pip install coveralls
  - python setup.py -q install
before_script:
  # append Test DB connection string to setup.cfg
  - echo $TESTDB >> setup.cfg
  # append Driver location to odbc config
  - echo DRIVER=$TRAVIS_BUILD_DIR/driver/libexaodbc-uo2214.so >> odbcconfig/odbcinst.ini
  
# command to run tests
script: python run_tests.py

after_success:
  coveralls
